### ISSUE TITLE
Images handling (as page attachments, not external URLs)

### ISSUE THREAD

**Issue by towi** [szn/confluence.md#1]
Great work, well thought through. My solution was not that elegant.

Do you have any idea how embedded images could be handled? Will you maybe add that? Or if you have an idea for an approach I could maybe add that.
Thanks, towi.

**Comment by szn** [comment]
Hi @towi 

I believe I found a solution for that. This shouldn't be a big deal:

[Solved: add visible images to Confluence using python](https://community.atlassian.com/t5/Confluence-questions/add-visible-images-to-Confluence-using-python/qaq-p/1785530)

I'll work on that.
