### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by Majlanky** [szn/confluence.md#16]
Hi, would it be possible to add mermaid extra (processor) mentioned on https://github.com/trentm/python-markdown2/wiki/Extras ? It would be fine to make the extras configurable through command parameters.

**Comment by szn** [comment]
Sounds exciting – I am a big fan of Mermaid.

Sadly, the solution isn't as trivial as expected. Adding one `extra` parameter to markdown2 is not enough as this does not generate an image file. Additional javascript is needed to convert mermaid code into a graph (as described here https://github.com/trentm/python-markdown2/wiki/mermaid). Loading external .js is not allowed on Confluence.

I would have to extract the mermaid code, convert it into svg/png, upload it to Confluence, and link it properly. This is definitely worth the effort but I can't estimate when I'll be able to do that.
