### ISSUE TITLE
Support for Jira Issue linking

### ISSUE THREAD

**Issue by rj93** [szn/confluence.md#17]
Hi,

I was looking for a way to automatically link to a Jira ticket given it's URL. For example, if you were to paste a Jira tickets URL when editing a page it will create an inline link that includes the ticket number, title, and it's status. 

I've had a look around and I can't seem to find anything in the docs for how to achieve this, so this might not actually be possible. The closest thing I've found is this [blog](https://www.atlassian.com/blog/confluence/link-jira-issues-to-confluence-pages-automatically) that mentions

> 3. Embed issues with copy and paste
> Autoconvert (AKA magic) makes producing reports of issues, backlogs, and tasks as easy as copy and paste. Simply paste a link from Jira into Confluence and watch it turn into a Smart Link. You can display this as a URL, a link, or a card view, which serves up metadata about the issue.

But I can't seem to find anything on how that would need to be represented in markdown, or HTML.

Example markdown:

```markdown
Jira IDs
* https://your-domain.atlassian.net/browse/ABC-123
* https://your-domain.atlassian.net/browse/ABC-456
```

Options I've tried:
* Jira ID - `ABC-123`
* Plain URL (this isn't even represented as link) - `https://your-domain.atlassian.net/browse/ABC-123`
* Markdown link - `[https://your-domain.atlassian.net/browse/ABC-123](https://your-domain.atlassian.net/browse/ABC-123)`

Any insight on if this would be possible, and how to achieve it would be appreciated.

**Comment by szn** [comment]
Hi @rj93,

That sounds interesting. I am a developer of [Smart Issue](https://marketplace.atlassian.com/apps/1224608/smart-issue-view-for-confluence?tab=overview&hosting=cloud), a Confluence macro that allows custom Jira snippets to be embedded on a confluence page. Maybe it's a match.

What `confluence.md` could do is:

1. Find pasted Jira tickets (it's easy as it's aware of your cloud domain, so it's `https://[your-domain].atlassian.net/browse/[letters-numbers]-[numbers]`
2. Request issue details via Jira API
3. Covert it to a regular HTML link with requested details

This could also work with a custom markdown such as `[JD-123]` where `confluence.md` would assume it's a Jira ticket.

This can work this way BUT you must be aware, that such a link would be static. In other words, once an issue changes status, it would not be affected on a confluence page.

In my case (sprint summary page generation) it's preferred. I want a frozen status of an issue on the day of sprint closing. But this can be confusing.

What's your thought?

**Comment by rj93** [comment]
Hey @szn, thanks for the quick reply. 

I can confirm that your new version works for static statuses, that I think could work (we can just schedule our pipeline to periodically to get the latest statuses).

Thanks a lot, tool is super useful 👍

**Comment by szn** [comment]
Hi @rj93 update to the newest `0.3.1` version from regular PYPI:

```
python -m pip install --upgrade confluence.md
```

Then run it with a new `--convert_jira` option. 

It works with links (so you can paste a Jira link as is), and issue keys in square brackets (as in the draft you already tested).

This version adds an issue-type icon before the issue key.
