### ISSUE TITLE
Error 'str' object has no attribute 'get' when trying to update page

### ISSUE THREAD

**Issue by revoldver** [szn/confluence.md#23]
Hi, dear @szn !

Got new error with Confluence v8.5.4 and confluence.md v0.4.4 (current):
`'str' object has no attribute 'get'`
when trying to update page with command:

`confluence.md --user "" --token $CONFLUENCE_USER_PASSWORD --no_verify_ssl --url https://confluence.mycompany.name create --file page-info.md --parent_id $PARENT_PAGE_ID --title "$PAGE_TITLE" --overwrite`
(user is empty when working with access token only).

The command above works well 5 months ago with confluence.md v0.2.8.

Thank you!

**Comment by szn** [comment]
Hi @revoldver,

Can you please rerun this command with `--verbose`? That would help me a lot.

SN

**Comment by szn** [comment]
I can't reproduce this.
