### ISSUE TITLE
Question about the 'create' call

### ISSUE THREAD

**Issue by Cliabhach** [szn/confluence.md#3]
Hi! I tried this out to upload a new file and had a little trouble. Surely the check should read `assert not page_id_from_meta or overwrite, ...`, so that you can create a file that doesn't have an id _and_ without using `overwrite`? Or perhaps I misunderstand what it's doing.

https://github.com/szn/confluence.md/blob/8d039a124d3946c891a071fb04ad6a8251e849dd/src/md2cf/utils/confluencemd.py#L74

**Comment by szn** [comment]
Hi @Cliabhach,

This is a bug introduced in the 1.1.2 version. Thank you for raising that!

Please upgrade to 1.1.3 with `python -m pip install --upgrade confluence.md`.

**Comment by Cliabhach** [comment]
Ah, perfect. I can confirm that the fix works!
