### ISSUE TITLE
No space or no content type, or setup a wrong version type set to content, or status param is not draft and status content is current

### ISSUE THREAD

**Issue by zhangyang2057** [szn/confluence.md#8]
I use the following command to update my confluence page on gitlab CI.
`$ confluence.md --url ${CF_HOST} --user ${CF_USERNAME} -t ${CF_TOKEN} --page_id ${CF_PAGE_ID} update --file infer_report*.md`

The update can be executed successfully at the first time, but failed with the second update
`10:09:00 >  Updates page content based on given page_id or metadata in Markdown file        
10:09:00 > Updating page `108169787` based on `md_file` file
10:09:00 > Converting MD to HTML
10:09:00 > Getting page title from page id `108169787`
10:09:00 > Updating page_id `108169787` titled `new benchmark test`
10:09:00 > No space or no content type, or setup a wrong version type set to content, or status param is not draft and status content is current
`

Is there any suggestion?

**Comment by zhangyang2057** [comment]
There are some '<br>'s in markdown, remove them can fix the issue.

**Comment by carlosjgp** [comment]
@zhangyang2057 what was the character or block breaking this?

Could you add a before and after example, please?
